TARGET = $(CX_SRC)/build/kern.a
TYPE = LIBRARY
OBJS = cx_drv.o cx_sched.o cx_semaphore.o \
	   cx_init.o cx_mem.o cx_event.o cx_signal.o \
	   cx_sched_console.o cx_mutex.o cx_waitgroup.o
include $(CX_SRC)/make/os.mk
